// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCruz3BTgxAMinD_41A5JbS2oZyp8LFugg',
    appId: '1:255039186440:web:5d29ca25e3e65362dd93bd',
    messagingSenderId: '255039186440',
    projectId: 'mc-co-9995d',
    authDomain: 'mc-co-9995d.firebaseapp.com',
    storageBucket: 'mc-co-9995d.firebasestorage.app',
    measurementId: 'G-CGJ1YH24YX',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5k_BH2w8Hrkui-6beZ55kBfsUl3jEKY',
    appId: '1:255039186440:android:6764629532904b0cdd93bd',
    messagingSenderId: '255039186440',
    projectId: 'mc-co-9995d',
    storageBucket: 'mc-co-9995d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhUy551iudGnXuZXMfGqkPugb5eWtWpYI',
    appId: '1:255039186440:ios:f7271b1f49ac2facdd93bd',
    messagingSenderId: '255039186440',
    projectId: 'mc-co-9995d',
    storageBucket: 'mc-co-9995d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhUy551iudGnXuZXMfGqkPugb5eWtWpYI',
    appId: '1:255039186440:ios:f7271b1f49ac2facdd93bd',
    messagingSenderId: '255039186440',
    projectId: 'mc-co-9995d',
    storageBucket: 'mc-co-9995d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCruz3BTgxAMinD_41A5JbS2oZyp8LFugg',
    appId: '1:255039186440:web:fbab4c9fe6035a16dd93bd',
    messagingSenderId: '255039186440',
    projectId: 'mc-co-9995d',
    authDomain: 'mc-co-9995d.firebaseapp.com',
    storageBucket: 'mc-co-9995d.firebasestorage.app',
    measurementId: 'G-7BYMTNBR2X',
  );
}
